[*]
jinja = true
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
n-gpu-layers = all
split-mode = layer
tensor-split = 1,1
fit = off

[gpt-oss-20b-Q5_K_M]
ctx-size=65536
temp=1.0
top-p=1.0
top-k=0
min-p=0.0
repeat-penalty=1.0
presence-penalty=0.0
frequency-penalty=0.0
dry-multiplier=0

[Qwen3.6-27B-Q8_0]
mmproj=/models/mmproj/Qwen3.6-27B-mmproj-F16.gguf
ctx-size=65536
#threads = 12
#threads-batch = 12
#mlock = true
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[Qwen3.6-35B-A3B-UD-Q4_K_M]
mmproj=/models/mmproj/Qwen3.6-35B-A3B-mmproj-F16.gguf
mmproj-offload = true
ctx-size = 65536
#threads = 12
#threads-batch = 12
#mlock = true
temp=0.7
top-p=0.8
top-k=20
min-p=0.0
repeat-penalty=1.0
presence-penalty=1.5
