model_list:
  - model_name: reasoning
    litellm_params:
      model: openai/gpt-oss-20b-Q5_K_M
      api_base: http://192.168.1.15:8080/v1
      api_key: none

  - model_name: moe
    litellm_params:
      model: openai/Qwen3.6-35B-A3B-UD-Q4_K_M
      api_base: http://192.168.1.15:8080/v1
      api_key: none

  - model_name: dense
    litellm_params:
      model: openai/Qwen3.6-27B-Q8_0
      api_base: http://192.168.1.15:8080/v1
      api_key: none


litellm_settings:
  drop_params: true
  set_verbose: false

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
