version: "3.8"

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /srv/docker/searxng:/etc/searxng
    environment:
      - BASE_URL=http://192.168.1.15:8081/
      - INSTANCE_NAME=Felix-SearXNG
